# Generated by Django 6.0.7 on 2026-07-22 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name des Schenkers')),
                ('title', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('image', models.URLField(blank=True, help_text='URL zum Produktbild', null=True, verbose_name='Bild-URL')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preis')),
                ('urgency', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='1 = nicht so dringend, 5 = sehr dringend', verbose_name='Dringlichkeit')),
                ('is_available', models.BooleanField(default=True, verbose_name='Verfügbar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('gifted_at', models.DateTimeField(blank=True, null=True, verbose_name='Geschenkt am')),
            ],
            options={
                'verbose_name': 'Wunsch',
                'verbose_name_plural': 'Wünsche',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GiftTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giver_name', models.CharField(max_length=100, verbose_name='Name des Schenkers')),
                ('gifted_at', models.DateTimeField(auto_now_add=True, verbose_name='Geschenkt am')),
                ('is_reversed', models.BooleanField(default=False, verbose_name='Rückgängig gemacht')),
                ('wish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wunschliste.wish')),
            ],
            options={
                'verbose_name': 'Schenk-Transaktion',
                'verbose_name_plural': 'Schenk-Transaktionen',
                'ordering': ['-gifted_at'],
            },
        ),
    ]
