# Generated by Django 6.0.7 on 2026-07-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wunschliste', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='image_url',
            field=models.URLField(blank=True, help_text='Alternativ: URL zum Produktbild', null=True, verbose_name='Bild-URL'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='image',
            field=models.ImageField(blank=True, help_text='Produktbild hochladen', null=True, upload_to='wish_images/', verbose_name='Bild'),
        ),
    ]
