# Generated by Django 6.0.7 on 2026-07-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wunschliste', '0002_wish_image_url_alter_wish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung'),
        ),
    ]
